### PR TITLE
Add support for WireGuard VPN

### PR DESCRIPTION
**Pull request by MarcLandis**
- added Lua service for wireguard endpoint
- updated Grafana dashboard

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for this great idea. I wanted to implement this as well but was waiting for 7.50.

I would suggest 2 changes:
* instead of renaming the values it would be great to add the vpn type as a tag and use the value name for both services. Then old dashboard won't break and it can easily be added to new ones.
* when exporting the dashboard it is important to have the top row unfolded and all other rows folded. This way the changes in the dashboard are kept to the bare minimum. (It is quite silly how the rows are implemented in the json schema but 🤷‍♂️)

Would this be possible?

Thank you.

**Comment by MarcLandis** [comment]
Hi,

I will try to change it to your idea. Unfortunately I am not sure how to add a static tag in lua_services.append(...)

**Comment by bb-Ricardo** [comment]
Line 203 in your PR is a tag function which returns a dict with tags: `, "vpntype": "Wireguard"`

This tag needs to be added and where it's missing you just need to add the whole tag_function.

**Comment by bb-Ricardo** [comment]
Thank you, will have a look later this week.

**Comment by bb-Ricardo** [comment]
Hi,

yes, also from Berlin 😄

Just adding this PR

**Pull request merged**
