### PR TITLE
Influx v2 Support and multiple Fritzboxes

### PR DESCRIPTION
**Pull request by Multigestern**
This fork brings compatibility to InfluxDB V2.
It is also possible to monitor multiple Fritzboxes.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

I was just wondering. Are you aware that all of this is already implemented in the current version?

**Comment by Multigestern** [comment]
My fault, my bookmark was on an older release...

**Comment by Dreistein75** [comment]
Sorry, I didn't know where else to ask:
@bb-Ricardo you said that all the features from this PR is already implemented in the current version. But I cannot figure out how to monitor several FritzBoxes at once. Can you give me a link?

**Comment by bb-Ricardo** [comment]
Hi,

Yes, but 🙂.

For each FritzBox you need to run a separate instance of this script. They can all write to the same influxdb. You can even use the same config. You just need to set the fritzbox `box_tag` to a different value for each box monitored. You could do that using the environment variable `FRITZBOX_BOX_TAG`.

Does this description help?

**Comment by bb-Ricardo** [comment]
Closing this PR as it conflicts heavily with the current code base

**Pull request closed without merging**
