### PR TITLE
Enable queries via Lua for FritzBox FW > 7

### PR DESCRIPTION
**Pull request by tombirdberlin**

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for this PR. Just curious what issue do you have right now that this change is trying to solve?

**Comment by tombirdberlin** [comment]
Hi @bb-Ricardo,

thank you for asking.

I stumbled about missing _ha_*_ data like _ha_powermeter_power_ in my dashboards after updating to the new released FRITZ!OS-Version 8.00.

To my surprise this did not correlate with the update itself but stopped more than 10 days later when my _fritzinfluxdb_ container restarted while other data was still written to influxdb.

So I startet to investigate.

The logs of my container showed "2024-09-25 21:34:58 INFO: Disabling queries via Lua. Fritz!OS version must be at least 7.XX" after Restart

So I tried to enable this and my data is back in influxdb.

**Comment by bb-Ricardo** [comment]
There is a 8.X release out? Well that's news to me.

**Comment by bb-Ricardo** [comment]
Yes, indeed. Will merge this soon.
I'm testing the beta since a while and assumed they will stay with 7 😅

**Comment by bb-Ricardo** [comment]
release in version https://github.com/bb-Ricardo/fritzinfluxdb/releases/tag/v1.2.3

**Pull request merged**
