### PR TITLE
feat: add connection detail parsing for devices

### PR DESCRIPTION
**Pull request by muenzpraeger**
### What does this PR do?

This pull request adds the ability to parse connection detail values for each active network device.

Specifically it adds:
- Is part of Mesh
- Wifi frequency
- Upstream / Downstream speed

### What issues does this PR fix or reference?

#65

### Functionality Before

The above mentioned device details are not collected.

### Functionality After

The data extraction mechanism for device properties has been extended add additional information to InfluxDB.

Data that is extracted is stored in the `txt` key. Devices can have one or more property objects (usually mostly two like "Mesh" and "Speed"). The JSON snippet below shows the different variations from a `Fritz!Box 7490` on `Fritz!OS 7.29`.

```json
{
    "properties": [
        // Device is part of Mesh, i. e. Powerline or Repeater
        {
            "txt": "Mesh",
            "link": "",
            "class": "nexus text",
            "onclick": "",
            "svg": "/css/rd/icons/ic_nexus.svg"
        },
        // Connection speed for non-WiFi devices
        {
            "txt": "166 / 150 Mbit/s",
            "onclick": "",
            "icon": "",
            "link": ""
        },
        // Connection frequency and speed for WiFi devices
        {
            "txt": "2,4 GHz, 50 / 836 Mbit/s",
            "onclick": "",
            "icon": "",
            "link": ""
        },
        // Connection frequency only (edge case to be aware of, seen intermittently on Repeater device)
        {
            "onclick": "",
            "txt": "2,4 GHz",
            "icon": "",
            "link": ""
        }
    ]
}
```

Additionally this pull request also adds a new tag `name` to certain value entries, so that a value selection based on tag value is possible within Grafana 1.8.

wifi-over-time-example

### CODE REVIEW

**Comment by muenzpraeger** [comment]
@bb-Ricardo Let me know if that PR suits you. Python is not my main language that I use.

Specifically I'd be interested if there's a more elegant solution to check for the the RegEx value (without using NumPy, didn't  want to add another dependency).

**Comment by bb-Ricardo** [comment]
Hi,

first of all thank you for this high quality PR. Not seeing a description like this very often.

I had another look at the FritzBox user interface and found way more structured data here: "WLAN->Funknetz".

Example:
```json
{
    "pid": "wSet",
    "hide": {
        "rss": true,
        "mobile": true,
        "provServ": true,
        "liveTv": true,
        "dectMail": true,
        "dectRdio": true,
        "ssoSet": true,
        "liveImg": true
    },
    "time": [],
    "data": {
        "wlanSettings": {
            "protocol": "23",
            "hasTriband": false,
            "knownWlanDevices": [
                {
                    "type": "active",
                    "name": "Bathroom",
                    "delete": {
                        "deleteable": false,
                        "reason": "DEVICE_ACTIVE"
                    },
                    "uid": "landevice984",
                    "url": "http://192.168.178.32",
                    "bands": {
                        "ghz24": {
                            "mac": "60:01:94:00:00:00",
                            "cipher": "wpa2",
                            "rssi": 5,
                            "rate": {
                                "us": "54",
                                "ds": "72"
                            },
                            "props": "n/Wi-Fi 4, 20 MHz, WPA2, 1 x 1"
                        }
                    },
                    "ip": "192.168.178.32"
                },
                {
                    "uid": "landevice2137",
                    "name": "SkyNet-Mainframe",
                    "delete": {
                        "deleteable": false,
                        "reason": "DEVICE_ACTIVE"
                    },
                    "type": "active",
                    "bands": {
                        "ghz5": {
                            "mac": "88:66:5A:00:00:00",
                            "cipher": "wpa2",
                            "rssi": 4,
                            "rate": {
                                "us": "866",
                                "ds": "1170"
                            },
                            "props": "ac/Wi-Fi 5, 80 MHz, WPA2, 3 x 3"
                        }
                    },
                    "ip": "192.168.178.83"
                },
                {
                    "uid": "landevice4515",
                    "name": "Printer",
                    "delete": {
                        "deleteable": true,
                        "reason": "CONFIRM_DELETE"
                    },
                    "type": "passive",
                    "bands": {
                        "ghz24": {
                            "mac": "00:22:69:00:00:00",
                            "cipher": "none",
                            "rssi": 0,
                            "rate": {
                                "us": 0,
                                "ds": 0
                            },
                            "props": "nicht verbunden"
                        }
                    },
                    "ip": "192.168.178.76"
                }
            ]
        }
    },
    "sid": "XYZ"
}
```

Would rather use this as data input.

For Mesh the page "WLAN->Mesh Repeater" seems interesting. But I don't have any Mesh device, so not sure what we could get out of there.

There is actually way more to get there. Probably worth adding a complete dashboard at the end.

What do you think?

**Comment by bb-Ricardo** [comment]
Hi,

Good point. Also not a fan of inconsistent data between endpoints. 😄 

Then I would suggest to add a separate function which does the parsing with the desired returned value as second parameter.
Also should account for "GBit/s" values.

What do you think?

**Comment by bb-Ricardo** [comment]
Hi @muenzpraeger,

I just checked again and Gbit/s does not show up in the host view it will report `5 GHz, 1300 / 1300 Mbit/s` so just ignore this comment.

I'm finally done with the dashboard conversion to Flux. So I might just merge this as well and rework it a bit.

**Comment by muenzpraeger** [comment]
Sure, whatever approach works best.

As long as I can move off my custom form at some point in the future. ;-)

**Pull request merged**
